### ISSUE TITLE
Outcome is way different from the outcome published using the same code

### ISSUE THREAD

**Issue by LHMphaphuli** [Energy-Data-Science-Collaboration-Forum/ps-demand-forecasting#1]
[model_performance_20230721_110726.csv](https://github.com/Energy-Data-Science-Collaboration-Forum/ps-demand-forecasting/files/12122747/model_performance_20230721_110726.csv)

Without changing the code I am getting Model_Performance as per the attached file. Please confirm if you are getting the published results using the same clone.

**Comment by adfi** [comment]
Hi @LHMphaphuli ,  I have re-run the code and my results are almost the same:

|Model|MAE|MAPE|
---|---|---|
|GLM_63|37.83638|2.80327|
|PS_GAM|166.726|8.0817|

The performance of the *GLM_63* model is identical but the *PS_GAM* model is different. I put that down to the randomness that is inherent in how the Prophet model is trained. I suspect the small sample size makes it worse.

Which brings me to the cause of these performance values. When you run *main.py* with the default values it uses the sample datasets that are included with the repository. We thought it would enable you to test your python setup and also give you an idea of what the input data should look like.

Now that we know your setup works you should view the README in the *data* folder to see how to download larger datasets. Note that our performance values were obtained with data from January 2019 to January 2023. Please let us know if you run into any problems or have any other questions.
